# fly.toml app configuration file generated for holthe-demo on 2023-07-21T20:11:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "holthe-demo"
primary_region = "dfw"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
